---
title: "Habitatfiche"
date: "`r Sys.Date()`"
output: html_document
params: 
  Versie: "Versie 3"
  Habitatsubtype: "4010"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, include=FALSE}
library(RODBC)
library(dplyr)
library(xtable)
library(tidyr)

```

```{r inladen_gegevens}

query_habitatfiche <- sprintf(
  "SELECT Habitatsubtype.Habitatcode_subtype, Habitatsubtype.Habitatnaam_subtype,
    Criterium.Naam AS Criterium, Indicator.Naam As Indicator, 
    Indicator_habitat.Beschrijving, Indicator_habitat.Beschrijving_naSoorten, 
    Indicator_habitat.Maatregelen, Indicator_habitat.Opmerkingen, Indicator_habitat.Referenties,
    Indicator_habitat.NiveauSoortenlijstFiche, Indicator_habitat.SoortengroepID
  FROM ((Indicator_habitat INNER JOIN Habitatsubtype ON Indicator_habitat.HabitatsubtypeID = Habitatsubtype.Id)
          INNER JOIN (Indicator INNER JOIN Criterium on Indicator.CriteriumID = Criterium.Id)
                        ON Indicator_habitat.IndicatorID = Indicator.Id)
          INNER JOIN Versie ON Indicator_habitat.VersieID = Versie.Id
  WHERE (Versie.VersieLSVI='%s') AND (Habitatsubtype.Habitatcode_subtype='%s')",
  params$Versie, params$Habitatsubtype
)
  

query_beoordelingsfiche <- sprintf(
  "SELECT Habitatsubtype.Habitatcode_subtype, Habitatsubtype.Habitatnaam_subtype,
    Criterium.Naam AS Criterium, Indicator.Naam As Indicator, 
    Indicator_beoordeling.Opmerkingen, Indicator_beoordeling.Referenties,
    Beoordeling.Kwaliteitsniveau, Beoordeling.Beoordeling_letterlijk
  FROM (((Indicator_habitat INNER JOIN Habitatsubtype ON Indicator_habitat.HabitatsubtypeID = Habitatsubtype.Id)
              INNER JOIN Versie ON Indicator_habitat.VersieID = Versie.Id)
          INNER JOIN IndicatortabellenKoppeling ON Indicator_habitat.Id = IndicatortabellenKoppeling.Indicator_habitatID)
        INNER JOIN 
              ((Indicator_beoordeling INNER JOIN Beoordeling ON Indicator_beoordeling.Id = Beoordeling.Indicator_beoordelingID)
            INNER JOIN (Indicator INNER JOIN Criterium on Indicator.CriteriumID = Criterium.Id)
                        ON Indicator_beoordeling.IndicatorID = Indicator.Id)
          ON IndicatortabellenKoppeling.Indicator_beoordelingID = Indicator_beoordeling.Id
  WHERE (Versie.VersieLSVI='%s') AND (Habitatsubtype.Habitatcode_subtype='%s')",
  params$Versie, params$Habitatsubtype
)
  

query_soortengroep <- "SELECT Soortengroep.Id as SoortengroepID, Soortengroep.Naam, Soortengroep.Omschrijving, 
                        SoortengroepSoort.SoortID, SoortengroepSoort.SoortensubgroepID
                       FROM Soortengroep INNER JOIN SoortengroepSoort ON Soortengroep.Id = SoortengroepSoort.SoortengroepID"

query_soort <- "SELECT Soort.Id AS SoortID, Soort.WetNaam, Soort.NedNaam FROM Soort"

query_versie <- sprintf("SELECT * FROM Versie WHERE Versie.VersieLSVI='%s'", params$Versie)


LSVIdb <- odbcConnectAccess2007("C://Users/els.lommelen@inbo.be/els.lommelen@inbo.be/10194_Controlelijsten/Output/LSVIdb_v4.accdb")

Habitatfiche <- sqlQuery(LSVIdb, query_habitatfiche, stringsAsFactors = FALSE)

Beoordelingsfiche <- sqlQuery(LSVIdb, query_beoordelingsfiche, stringsAsFactors = FALSE)

Soortengroep <- sqlQuery(LSVIdb, query_soortengroep, stringsAsFactors = FALSE)

Soort <- sqlQuery(LSVIdb, query_soort, stringsAsFactors = FALSE)

Versie <- sqlQuery(LSVIdb, query_versie, stringsAsFactors = FALSE)

odbcClose(LSVIdb)

```


##Habitattype `r Habitatfiche[1,"Habitatcode_subtype"]`: `r Habitatfiche[1,"Habitatnaam_subtype"]`

###Habitatkarakteristieken

```{r results='asis'}
Soortengroepselectie <- Soortengroep %>%
  filter(SoortengroepID %in% Habitatfiche$SoortengroepID) %>%
  left_join(Soortengroep, by = c("SoortensubgroepID" = "SoortengroepID"), suffix = c(".1", ".2"))

#bij het veralgemenen van deze functie moet deze left_join herhaald worden volgens het maximale aantal niveaus vermeld in Indicator_habitat$NiveauSoortenlijstFiche

Soortengroepselectie$SoortID <- 
  ifelse(!is.na(Soortengroepselectie$SoortID.1),Soortengroepselectie$SoortID.1, Soortengroepselectie$SoortID.2)

#ook dit moet verder uitgebreid worden bij het veralgemenen van de functie, evt. door alle SoortID's te selecteren en de niet-NA eruit te kiezen? NEE, hier moet rekening gehouden worden met het niveau vermeld in tabel Indicator_habitat! (soms moet ook het genus of de groepsnaam vermeld worden en niet de soortnaam)
#ook voor hetgeen volgt zou nog een algemene werkwijze toegevoegd moeten worden, meer specifiek onder 'group_by'

SoortenKoppeling <- Soortengroepselectie %>%
  left_join(Soort, by = c("SoortID" = "SoortID")) %>%
  mutate_(
    WetNaamKort = ~
      gsub(
        pattern = "^([[:alpha:]]*) ([[:alpha:]]*) (.*)",
        replacement = "\\1 \\2",
        x = WetNaam
      ),
    TotNaam = ~ sprintf("%s (_%s_)", NedNaam, WetNaamKort)
  ) %>%
  arrange_(~ TotNaam) %>%
  group_by_(
    ~ SoortengroepID,
    ~ Naam.1,
    ~ Omschrijving.1,
    ~ SoortensubgroepID,
    ~ Naam.2,
    ~ Omschrijving.2,
    ~ SoortensubgroepID.2
  ) %>%
  summarise_(
    Soortenlijst = ~ paste(as.vector(TotNaam), collapse = ", ")
  ) %>%
  ungroup() %>%
  mutate_(
    Soortenlijst = ~ ifelse(is.na(Omschrijving.2), Soortenlijst, 
                          paste("**",Omschrijving.2,":** ",Soortenlijst, sep=""))
  ) %>%
  group_by_(
    ~ SoortengroepID,
    ~ Naam.1,
    ~ Omschrijving.1
  ) %>%
  summarise_(
    Soortenlijst = ~ paste(as.vector(Soortenlijst), collapse = ",  ")
  ) %>%
  ungroup()

paste2 <- function(...,sep=", ") {
    L <- list(...)
    L <- lapply(L,function(x) {x[is.na(x)] <- ""; x})
    gsub(paste0("(^",sep,"|",sep,"$)"),"",
                gsub(paste0(sep,sep),sep,
                     do.call(paste,c(L,list(sep=sep)))))
}

Habitatfiche2 <- Habitatfiche %>%
  left_join(SoortenKoppeling, by = c("SoortengroepID" = "SoortengroepID")) %>%
  mutate_(
    Beschrijving = ~ paste2(Beschrijving, Soortenlijst, Beschrijving_naSoorten, sep = " ")
  )


for(Criterium in unique(Habitatfiche$Criterium)){
  print(Criterium)
  Habitatkarakteristieken <- 
    xtable(Habitatfiche2[Habitatfiche2$Criterium==Criterium,
                        c("Indicator","Beschrijving","Maatregelen","Opmerkingen","Referenties")])
  print(Habitatkarakteristieken, type = "html")
}

```


###Beoordelingsmatrix

```{r results='asis', message=FALSE, warning=FALSE}
Beoordelingsfiche <- Beoordelingsfiche %>%
  inner_join(data.frame(Kwaliteitsniveau=c(1,2), Referentieniveau = c(Versie$Kwaliteitsniveau1,Versie$Kwaliteitsniveau2), stringsAsFactors = FALSE)) %>%
  select(-Kwaliteitsniveau)%>%
  spread(key = Referentieniveau, value = Beoordeling_letterlijk)

for(Criterium in unique(Habitatfiche$Criterium)){
  print(Criterium)
  Beoordelingsmatrix <- 
    xtable(Beoordelingsfiche[Beoordelingsfiche$Criterium==Criterium,
                        c("Indicator","Gunstige staat","Streefwaarde","Opmerkingen","Referenties")])
  print(Beoordelingsmatrix, type = "html")
}

```

