---
title: "Rapportage LSVI-indicatoren"
date: "`r Sys.Date()`"
output: html_document
params: 
  ConnectieLSVIhabitats: "dummy"
  Versie: "Versie 2.0"
  Habitatgroep: "Heiden"
  Habitattype: "4010"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, include=FALSE}
library(dplyr)
library(LSVI)
library(rmarkdown)
library(knitr)

```

```{r gegevens_inladen}

if (
  inherits(params$ConnectieLSVIhabitats, "DBIConnection") |
    inherits(ConnectieLSVIhabitats, "Pool")
) {
  ConnectieLSVIhabitats <- params$ConnectieLSVIhabitats
} else {
  #print("Connectiefout!")
  ConnectieLSVIhabitats <- connecteerMetLSVIdb()
}

Indicatoren <- 
  selecteerIndicatoren(
    ConnectieLSVIhabitats = ConnectieLSVIhabitats,
    Versie = params$Versie,
    Habitatgroep = params$Habitatgroep, 
    Habitattype = params$Habitattype,
    HabitatnamenToevoegen = TRUE
  ) %>%
  select(
    .data$Versie, .data$Habitatgroepnaam, .data$Habitattype, .data$Habitatnaam,
    .data$Habitatsubtype, .data$Habitatsubtypenaam
  ) %>%
  distinct()

```



```{r habitatfiches, include=FALSE, message=FALSE, warning=FALSE, results='asis'}

Uitvoer <- NULL

for (VersieRapportdeel in unique(Indicatoren$Versie)) {
  Uitvoer <- c(Uitvoer, paste("#", VersieRapportdeel, sep = ""))
  VersieIndicatoren <- Indicatoren %>%
    filter(.data$Versie == VersieRapportdeel)
  for (Habitatgroep in unique(VersieIndicatoren$Habitatgroepnaam)) {
    Uitvoer <- c(Uitvoer, paste("##",Habitatgroep, sep = ""))
    Subset <- VersieIndicatoren %>%
      filter(.data$Habitatgroepnaam == Habitatgroep)
    for (Habitat in unique(as.character(Subset$Habitattype))) {
      Subsubset <- Subset %>%
        filter(.data$Habitattype == Habitat)
      Habitatnaam <- ifelse(is.na(unique(Subsubset$Habitatnaam)),
                            "",
                            paste(": ", unique(Subsubset$Habitatnaam), sep = ""))
      Uitvoer <- c(Uitvoer, paste("###Habitattype ", Habitat, Habitatnaam, "\n", sep = ""))
      for (HabitatsubtypeFiche in unique(as.character(Subsubset$Habitatsubtype))) {
        Habitatsubtypenaam <- 
          ifelse(is.na(unique((Subsubset %>% 
                                filter(.data$Habitatsubtype == HabitatsubtypeFiche))$Habitatsubtypenaam)),
                 "",
                 paste(": ", unique((Subsubset %>% 
                                filter(.data$Habitatsubtype == HabitatsubtypeFiche))$Habitatsubtypenaam), sep = ""))
        if (HabitatsubtypeFiche != Habitat) {
          Uitvoer <- 
            c(Uitvoer,
              paste("####Habitatsubtype ", HabitatsubtypeFiche, 
                    Habitatsubtypenaam, "\n", sep = ""))
        }
        Uitvoer <- 
          c(Uitvoer,
            knit_child("Habitatfiche.Rmd"))
        
      }
    }

  }
}



```


```{r output, results='asis'}
cat(Uitvoer, sep = "\n")
```

